import { useState } from 'react'
import { useBudget } from '../contexts/BudgetContext'
import { formatCurrency, formatDate, getCurrentMonth, formatMonth } from '../utils/formatters'
import { getCategoryInfo } from '../utils/categories'

function changeMonth(month, delta) {
  const [y, m] = month.split('-').map(Number)
  const d = new Date(y, m - 1 + delta, 1)
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`
}

export default function ExportData() {
  const { transactions, getMonthlyTotal, getBalance } = useBudget()
  const [month, setMonth] = useState(getCurrentMonth())
  const [allTime, setAllTime] = useState(false)
  const [copied, setCopied] = useState(false)

  const filtered = allTime ? transactions : transactions.filter(t => t.date.startsWith(month))
  const income = allTime
    ? transactions.filter(t => t.type === 'income').reduce((s, t) => s + t.amount, 0)
    : getMonthlyTotal(month, 'income')
  const expenses = allTime
    ? transactions.filter(t => t.type === 'expense').reduce((s, t) => s + t.amount, 0)
    : getMonthlyTotal(month, 'expense')
  const balance = income - expenses

  const exportCSV = () => {
    const headers = 'Date,Type,Category,Amount,Note,Recurring\n'
    const rows = filtered.map(t => {
      const info = getCategoryInfo(t.category)
      return `${t.date},${t.type},${info.name},${t.amount},"${(t.note || '').replace(/"/g, '""')}",${t.recurring || 'none'}`
    }).join('\n')
    const csv = headers + rows
    const blob = new Blob([csv], { type: 'text/csv' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `doaide-budget-${allTime ? 'all' : month}.csv`
    a.click()
    URL.revokeObjectURL(url)
  }

  const exportPDF = async () => {
    const { default: jsPDF } = await import('jspdf')
    await import('jspdf-autotable')

    const doc = new jsPDF()
    const title = allTime ? 'All Time Budget Report' : `Budget Report — ${formatMonth(month)}`

    doc.setFontSize(20)
    doc.setTextColor(240, 180, 41)
    doc.text('DoAide Budget', 14, 22)

    doc.setFontSize(14)
    doc.setTextColor(0, 0, 0)
    doc.text(title, 14, 34)

    doc.setFontSize(11)
    doc.text(`Income: ${formatCurrency(income)}`, 14, 46)
    doc.text(`Expenses: ${formatCurrency(expenses)}`, 14, 54)
    doc.text(`Balance: ${formatCurrency(balance)}`, 14, 62)

    const tableData = filtered.map(t => {
      const info = getCategoryInfo(t.category)
      return [t.date, t.type, info.name, formatCurrency(t.amount), t.note || '', t.recurring || 'none']
    })

    doc.autoTable({
      startY: 72,
      head: [['Date', 'Type', 'Category', 'Amount', 'Note', 'Recurring']],
      body: tableData,
      styles: { fontSize: 9 },
      headStyles: { fillColor: [240, 180, 41] },
    })

    const pageCount = doc.internal.getNumberOfPages()
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i)
      doc.setFontSize(8)
      doc.setTextColor(150)
      doc.text('Generated by DoAide Budget — budget.doaide.com', 14, doc.internal.pageSize.height - 10)
    }

    doc.save(`doaide-budget-${allTime ? 'all' : month}.pdf`)
  }

  const shareSummary = async () => {
    const period = allTime ? 'All Time' : formatMonth(month)
    const text = `📊 My ${period} Budget Summary
💰 Income: ${formatCurrency(income)}
💸 Expenses: ${formatCurrency(expenses)}
💵 Balance: ${formatCurrency(balance)}

Track your budget free at budget.doaide.com`

    try {
      await navigator.clipboard.writeText(text)
    } catch {
      const ta = document.createElement('textarea')
      ta.value = text
      document.body.appendChild(ta)
      ta.select()
      document.execCommand('copy')
      document.body.removeChild(ta)
    }
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className="tool-page">
      <div className="tool-card">
        <h2 className="tool-title">📥 Export & Share</h2>

        <div className="export-period">
          <label className="checkbox-label">
            <input
              type="checkbox"
              checked={allTime}
              onChange={e => setAllTime(e.target.checked)}
            />
            All time
          </label>
          {!allTime && (
            <div className="month-selector inline">
              <button className="month-nav-btn" onClick={() => setMonth(m => changeMonth(m, -1))}>‹</button>
              <span className="month-display">{formatMonth(month)}</span>
              <button className="month-nav-btn" onClick={() => setMonth(m => changeMonth(m, 1))}>›</button>
            </div>
          )}
        </div>

        <div className="export-summary">
          <div className="export-stat">
            <span className="export-stat-label">Transactions</span>
            <span className="export-stat-value">{filtered.length}</span>
          </div>
          <div className="export-stat">
            <span className="export-stat-label">Income</span>
            <span className="export-stat-value income">{formatCurrency(income)}</span>
          </div>
          <div className="export-stat">
            <span className="export-stat-label">Expenses</span>
            <span className="export-stat-value expense">{formatCurrency(expenses)}</span>
          </div>
          <div className="export-stat">
            <span className="export-stat-label">Balance</span>
            <span className="export-stat-value">{formatCurrency(balance)}</span>
          </div>
        </div>

        <div className="export-options">
          <button className="export-btn csv" onClick={exportCSV} disabled={filtered.length === 0}>
            <span className="export-btn-icon">📊</span>
            <span>Export CSV</span>
          </button>
          <button className="export-btn pdf" onClick={exportPDF} disabled={filtered.length === 0}>
            <span className="export-btn-icon">📄</span>
            <span>Export PDF</span>
          </button>
          <button className="export-btn share" onClick={shareSummary}>
            <span className="export-btn-icon">📤</span>
            <span>{copied ? 'Copied!' : 'Share Summary'}</span>
          </button>
        </div>
      </div>

      {filtered.length > 0 && (
        <div className="tool-card">
          <h3>Preview ({filtered.length} transactions)</h3>
          <div className="amortization-scroll">
            <table className="amortization-table">
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Type</th>
                  <th>Category</th>
                  <th>Amount</th>
                  <th>Note</th>
                </tr>
              </thead>
              <tbody>
                {filtered.slice(0, 20).map(t => {
                  const info = getCategoryInfo(t.category)
                  return (
                    <tr key={t.id}>
                      <td>{t.date}</td>
                      <td>{t.type}</td>
                      <td>{info.emoji} {info.name}</td>
                      <td className={t.type}>{formatCurrency(t.amount)}</td>
                      <td>{t.note || '—'}</td>
                    </tr>
                  )
                })}
              </tbody>
            </table>
            {filtered.length > 20 && <p className="table-note">Showing 20 of {filtered.length}</p>}
          </div>
        </div>
      )}
    </div>
  )
}
